version: '3.8'

services:
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    ports:
      - "4444:4444"  # Expose Selenium on port 4444
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: willhaben_crawler_app
    depends_on:
      - selenium
    ports:
      - "5000:5000"  # Expose the Flask app to localhost:5000
    volumes:
      - ./src/data:/app/src/data  # Persist data and config storage
    environment:
      FLASK_APP: app.py
      FLASK_ENV: production
      SELENIUM_URL: "http://selenium:4444/wd/hub"  # Point to the Selenium container
    restart: always  # Automatically restart on failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 5s
      retries: 3
